// mockup/src/components/TaskCard.tsx
import { useDrag } from 'react-dnd';
import { Card } from './ui/card';
import { Badge } from './ui/badge';
import { Task } from '../types';
import { Clock, User } from 'lucide-react';

interface TaskCardProps {
  task: Task;
  onClick: () => void;
}

export function TaskCard({ task, onClick }: TaskCardProps) {
  const [{ isDragging }, drag] = useDrag(() => ({
    type: 'TASK',
    item: { id: task.id },
    collect: (monitor) => ({
      isDragging: !!monitor.isDragging(),
    }),
  }));

  const getTagColor = (tag: string) => {
    switch (tag) {
      case 'order':
        return 'bg-rose-100 text-rose-700 border-rose-200';
      case 'prep':
        return 'bg-blue-100 text-blue-700 border-blue-200';
      case 'practice':
        return 'bg-purple-100 text-purple-700 border-purple-200';
      case 'special':
        return 'bg-amber-100 text-amber-700 border-amber-200';
      case 'appetizer':
        return 'bg-emerald-100 text-emerald-700 border-emerald-200';
      default:
        return 'bg-slate-100 text-slate-700 border-slate-200';
    }
  };

  const timeAgo = (timestamp: number) => {
    const minutes = Math.floor((Date.now() - timestamp) / 60000);
    if (minutes < 1) return 'Just now';
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    return `${hours}h ago`;
  };

  return (
    <Card
      ref={drag}
      className={`p-4 cursor-pointer hover:shadow-md transition-all border border-slate-200 ${
        isDragging ? 'opacity-50' : 'opacity-100'
      }`}
      onClick={onClick}
    >
      <div className="space-y-3">
        <div>
          <h3 className="text-slate-900 mb-1">{task.title}</h3>
          {task.tableNumber && (
            <div className="text-slate-500 text-sm">Table {task.tableNumber}</div>
          )}
        </div>

        {task.orderItems && task.orderItems.length > 0 && (
          <div className="text-sm text-slate-600 space-y-1">
            {task.orderItems.map((item, idx) => (
              <div key={idx} className="flex items-center gap-2">
                <div className="w-1 h-1 rounded-full bg-slate-400" />
                {item}
              </div>
            ))}
          </div>
        )}

        <div className="flex items-center gap-2 flex-wrap">
          {task.tags.map((tag) => (
            <Badge key={tag} variant="outline" className={getTagColor(tag)}>
              {tag}
            </Badge>
          ))}
        </div>

        <div className="flex items-center gap-4 text-sm text-slate-500">
          {task.assignedTo && (
            <div className="flex items-center gap-1.5">
              <User className="w-3.5 h-3.5" />
              <span>{task.assignedTo}</span>
            </div>
          )}
          <div className="flex items-center gap-1.5 ml-auto">
            <Clock className="w-3.5 h-3.5" />
            <span>{timeAgo(task.createdAt)}</span>
          </div>
        </div>
      </div>
    </Card>
  );
}

// web/src/lib/components/flow/TaskCard.svelte
<script lang="ts">
	import type { TaskResponse } from '$lib/types/task';
	import { Badge } from '$lib/components/ui/badge';
	import { Clock, User } from 'lucide-svelte';

	interface Props {
		task: TaskResponse;
		stationMap: Map<string, string>;
	}

	let { task, stationMap }: Props = $props();

	// --- Helpers ---

	function priorityBadge(priority: number): {
		label: string;
		variant: 'default' | 'secondary' | 'destructive' | 'outline';
		class: string;
	} {
		switch (priority) {
			case 0:
				return { label: 'P0', variant: 'destructive', class: '' };
			case 1:
				return { label: 'P1', variant: 'default', class: 'bg-orange-600 text-white border-transparent' };
			case 2:
				return { label: 'P2', variant: 'secondary', class: '' };
			case 3:
				return { label: 'P3', variant: 'outline', class: '' };
			default:
				return { label: `P${priority}`, variant: 'outline', class: '' };
		}
	}

	function getStationName(stationId: string | null | undefined): string | null {
		if (!stationId) return null;
		return stationMap.get(stationId) ?? stationId.slice(0, 8);
	}

	function formatTimeAgo(dateStr: string): string {
		const date = new Date(dateStr);
		const now = new Date();
		const diffMs = now.getTime() - date.getTime();
		const diffMins = Math.floor(diffMs / 60_000);
		if (diffMins < 1) return 'Just now';
		if (diffMins < 60) return `${diffMins}m ago`;
		const diffHours = Math.floor(diffMins / 60);
		if (diffHours < 24) return `${diffHours}h ago`;
		const diffDays = Math.floor(diffHours / 24);
		return `${diffDays}d ago`;
	}

	let pBadge = $derived(priorityBadge(task.priority));
	let station = $derived(getStationName(task.stationId));
</script>

<a
	href="/flow/{task.id}"
	class="group block rounded-lg border border-border bg-card p-3 shadow-sm hover:border-primary/40 hover:shadow-md transition-all"
>
	<!-- Title -->
	<h4 class="text-sm font-medium text-foreground group-hover:text-primary transition-colors truncate">
		{task.title}
	</h4>

	<!-- Hierarchical ID -->
	<p class="mt-0.5 text-xs font-mono text-muted-foreground truncate">{task.id}</p>

	<!-- Badges row -->
	<div class="mt-2 flex flex-wrap items-center gap-1.5">
		<!-- Priority -->
		<Badge variant={pBadge.variant} class="text-[10px] px-1.5 py-0 h-5 {pBadge.class}">
			{pBadge.label}
		</Badge>

		<!-- Station -->
		{#if station}
			<Badge variant="outline" class="text-[10px] px-1.5 py-0 h-5">
				{station}
			</Badge>
		{/if}

		<!-- Quantity -->
		{#if task.quantity > 1}
			<Badge variant="outline" class="text-[10px] px-1.5 py-0 h-5">
				x{task.quantity}
			</Badge>
		{/if}
	</div>

	<!-- Footer: assignee + time ago -->
	<div class="mt-2 flex items-center justify-between text-[11px] text-muted-foreground">
		<div class="flex items-center gap-1">
			{#if task.assignedToId}
				<span
					class="inline-flex items-center justify-center size-5 rounded-full bg-primary/10 text-primary text-[10px] font-medium"
					title={task.assignedToId}
				>
					<User class="size-3" />
				</span>
			{/if}
		</div>
		<span class="flex items-center gap-0.5">
			<Clock class="size-3" />
			{formatTimeAgo(task.updatedAt)}
		</span>
	</div>
</a>
